<?php
declare(strict_types=1);

/**
 * Account security, for every role: phone number (change, reminder SMS) and two-factor authentication.
 *
 * Everything the page does goes through /api/phone.php and /api/2fa.php. This file only draws it.
 */

require_once __DIR__ . '/../auth.php';
require_once __DIR__ . '/../lib/Brand.php';
require_once __DIR__ . '/../lib/Phone.php';
require_once __DIR__ . '/../lib/TwoFactor.php';

if (!isLoggedIn()) {
    header('Location: /index.php?auth=login');
    exit;
}
$user = getCurrentUser();
if (!$user) {
    header('Location: /index.php');
    exit;
}

$lang = TranslationService::getLang() === 'en' ? 'en' : 'fr';
$pdo = Database::getInstance();
$extra = $pdo->prepare("SELECT sms_opt_in FROM users WHERE id = :id");
$extra->execute(['id' => $user['id']]);
$smsOptIn = (int)$extra->fetchColumn() === 1;
$tfaOn = !empty($user['totp_enabled_at']);
$recoveryLeft = $tfaOn ? TwoFactor::remainingRecovery($pdo, (int)$user['id']) : 0;
$required = in_array($user['role'], array_filter(array_map('trim', explode(',', (string)REQUIRE_2FA_ROLES))), true);
$home = ['promoter' => '/promoter/dashboard.php', 'teacher' => '/teacher/dashboard.php', 'student' => '/student/dashboard.php'][$user['role']] ?? '/index.php';

$T = [
 'fr' => [
  'title' => 'Sécurité du compte', 'back' => 'Retour au tableau de bord',
  'phone_h' => 'Numéro de téléphone', 'phone_none' => 'Aucun numéro vérifié.', 'phone_is' => 'Numéro vérifié :', 'phone_change' => 'Changer de numéro',
  'phone_label' => 'Nouveau numéro', 'phone_ph' => '6 12 34 56 78', 'send' => 'Envoyer le code', 'code_label' => 'Code reçu par SMS', 'verify' => 'Vérifier', 'cancel' => 'Annuler',
  'sent' => 'Code envoyé au :phone. Il est valable 10 minutes.', 'phone_saved' => 'Numéro vérifié et enregistré.',
  'sms_h' => 'Rappels par SMS', 'sms_p' => 'Recevoir un SMS quand une évaluation en direct est programmée pour l’un de vos cours. Les codes de vérification sont toujours envoyés.', 'sms_on' => 'Rappels activés', 'sms_off' => 'Rappels désactivés',
  'tfa_h' => 'Double authentification', 'tfa_p' => 'À chaque connexion, en plus du mot de passe, un code à 6 chiffres généré par une application sur votre téléphone (Google Authenticator, Microsoft Authenticator, Authy…).',
  'tfa_on' => 'Activée', 'tfa_off' => 'Désactivée', 'tfa_required' => 'Votre établissement exige la double authentification pour votre rôle. Activez-la pour continuer.',
  'tfa_start' => 'Activer la double authentification', 'tfa_step1' => '1. Scannez ce QR code avec votre application d’authentification.', 'tfa_manual' => 'Impossible de scanner ? Saisissez cette clé :', 'tfa_open' => 'Ouvrir dans l’application (sur téléphone)',
  'tfa_step2' => '2. Saisissez le code à 6 chiffres affiché par l’application.', 'tfa_confirm' => 'Activer', 'code' => 'Code',
  'rec_h' => 'Vos codes de secours', 'rec_p' => 'Gardez-les en lieu sûr. Chaque code ne sert qu’une fois et remplace l’application si vous perdez votre téléphone. Ils ne seront plus affichés.', 'rec_copy' => 'Copier', 'rec_print' => 'Imprimer', 'rec_dl' => 'Télécharger', 'rec_saved' => 'J’ai conservé mes codes', 'rec_copied' => 'Copié.',
  'rec_left' => 'Codes de secours restants :', 'rec_new' => 'Générer de nouveaux codes', 'rec_new_hint' => 'Saisissez un code de l’application. Les anciens codes cesseront de fonctionner.',
  'dis_h' => 'Désactiver', 'dis_p' => 'Mot de passe et code de l’application requis.', 'pw' => 'Mot de passe', 'dis_btn' => 'Désactiver la double authentification', 'dis_done' => 'Double authentification désactivée.', 'confirm_dis' => 'Désactiver la double authentification ?',
  'busy' => 'Un instant…', 'net' => 'Connexion impossible. Réessayez.', 'on_done' => 'Double authentification activée.',
 ],
 'en' => [
  'title' => 'Account security', 'back' => 'Back to the dashboard',
  'phone_h' => 'Phone number', 'phone_none' => 'No verified number.', 'phone_is' => 'Verified number:', 'phone_change' => 'Change number',
  'phone_label' => 'New number', 'phone_ph' => '6 12 34 56 78', 'send' => 'Send the code', 'code_label' => 'Code received by SMS', 'verify' => 'Verify', 'cancel' => 'Cancel',
  'sent' => 'Code sent to :phone. It is valid for 10 minutes.', 'phone_saved' => 'Number verified and saved.',
  'sms_h' => 'SMS reminders', 'sms_p' => 'Get a text message when a live evaluation is scheduled for one of your courses. Verification codes are always sent.', 'sms_on' => 'Reminders on', 'sms_off' => 'Reminders off',
  'tfa_h' => 'Two-factor authentication', 'tfa_p' => 'At every sign-in, on top of your password, a 6-digit code generated by an app on your phone (Google Authenticator, Microsoft Authenticator, Authy…).',
  'tfa_on' => 'On', 'tfa_off' => 'Off', 'tfa_required' => 'Your institution requires two-factor authentication for your role. Turn it on to continue.',
  'tfa_start' => 'Turn on two-factor authentication', 'tfa_step1' => '1. Scan this QR code with your authenticator app.', 'tfa_manual' => 'Cannot scan? Type this key instead:', 'tfa_open' => 'Open in the app (on a phone)',
  'tfa_step2' => '2. Enter the 6-digit code shown by the app.', 'tfa_confirm' => 'Turn on', 'code' => 'Code',
  'rec_h' => 'Your recovery codes', 'rec_p' => 'Keep them somewhere safe. Each code works once and replaces the app if you lose your phone. They will not be shown again.', 'rec_copy' => 'Copy', 'rec_print' => 'Print', 'rec_dl' => 'Download', 'rec_saved' => 'I have saved my codes', 'rec_copied' => 'Copied.',
  'rec_left' => 'Recovery codes left:', 'rec_new' => 'Generate new codes', 'rec_new_hint' => 'Enter a code from the app. The old codes will stop working.',
  'dis_h' => 'Turn off', 'dis_p' => 'Password and a code from the app are required.', 'pw' => 'Password', 'dis_btn' => 'Turn off two-factor authentication', 'dis_done' => 'Two-factor authentication turned off.', 'confirm_dis' => 'Turn off two-factor authentication?',
  'busy' => 'One moment…', 'net' => 'Could not connect. Please try again.', 'on_done' => 'Two-factor authentication is on.',
 ],
][$lang];
$h = fn($v) => htmlspecialchars((string)$v, ENT_QUOTES, 'UTF-8');
?>
<!DOCTYPE html>
<html lang="<?= $lang ?>">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex">
<title><?= $h($T['title']) ?> — StudyVibe</title>
<?= Brand::headLinks() ?>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,400..600&family=Hanken+Grotesk:wght@400;500;600;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="/assets/css/sv2.css">
<script>try { var s = localStorage.getItem('sv_dark'); if (s === '1' || (s === null && matchMedia('(prefers-color-scheme: dark)').matches)) document.documentElement.classList.add('dark'); } catch (e) {}</script>
<style>
  body { margin: 0; background: var(--paper); color: var(--ink); font: 16px/1.5 'Hanken Grotesk', system-ui, sans-serif; }
  main { max-width: 42rem; margin: 0 auto; padding: 1.5rem 1rem 4rem; }
  a { color: var(--clay); }
  h1 { font: 500 clamp(1.7rem, 4vw, 2.3rem)/1.15 'Fraunces', serif; margin: 1rem 0 1.5rem; }
  h2 { font: 500 1.35rem/1.2 'Fraunces', serif; margin: 0 0 .4rem; }
  section { background: var(--card); border: 1px solid var(--line); border-radius: 14px; padding: 1.25rem 1.25rem 1.4rem; margin-bottom: 1.25rem; }
  p { margin: .25rem 0 .75rem; color: var(--ink-2); }
  .row { display: flex; gap: .75rem; flex-wrap: wrap; align-items: center; }
  .pill { display: inline-block; padding: .15rem .65rem; border-radius: 999px; font-size: .8rem; font-weight: 700; background: var(--clay-soft); color: var(--clay); }
  .pill.ok { background: color-mix(in srgb, var(--pine) 16%, transparent); color: var(--pine); }
  label { display: block; font-weight: 600; margin: .75rem 0 .3rem; }
  input[type=text], input[type=tel], input[type=password] { width: 100%; max-width: 22rem; box-sizing: border-box; min-height: 46px; padding: .55rem .75rem; font: 500 1rem 'Hanken Grotesk', sans-serif; color: var(--ink); background: var(--paper); border: 1.5px solid var(--line-2); border-radius: 10px; }
  input:focus-visible, button:focus-visible, a:focus-visible { outline: 2px solid var(--clay); outline-offset: 2px; }
  .btn { min-height: 46px; padding: .5rem 1.1rem; border-radius: 10px; border: 1px solid var(--line-2); background: transparent; color: var(--ink); font: 600 .95rem 'Hanken Grotesk', sans-serif; cursor: pointer; }
  .btn.primary { background: var(--clay); border-color: var(--clay); color: #fff; }
  .btn.danger { color: var(--danger); border-color: var(--danger); }
  .btn:disabled { opacity: .55; cursor: progress; }
  .msg { margin: .75rem 0 0; padding: .55rem .75rem; border-radius: 10px; font-weight: 600; font-size: .92rem; }
  .msg.err { background: color-mix(in srgb, var(--danger) 12%, transparent); color: var(--danger); }
  .msg.ok { background: color-mix(in srgb, var(--pine) 14%, transparent); color: var(--pine); }
  .msg.warn { background: var(--clay-soft); color: var(--ink); }
  [hidden] { display: none !important; }
  .qr { width: 12rem; height: 12rem; background: #fff; border: 1px solid var(--line); border-radius: 12px; padding: .4rem; box-sizing: border-box; }
  .qr svg { width: 100%; height: 100%; display: block; }
  .secret { font: 600 1.05rem ui-monospace, SFMono-Regular, Menlo, monospace; letter-spacing: .06em; word-break: break-all; user-select: all; }
  .codes { display: grid; grid-template-columns: repeat(auto-fill, minmax(9.5rem, 1fr)); gap: .5rem; margin: .75rem 0; padding: 0; list-style: none; }
  .codes li { font: 600 1rem ui-monospace, SFMono-Regular, Menlo, monospace; padding: .45rem .6rem; background: var(--paper); border: 1px dashed var(--line-2); border-radius: 8px; text-align: center; }
  .toggle { display: flex; gap: .6rem; align-items: center; min-height: 44px; font-weight: 600; cursor: pointer; }
  .toggle input { width: 1.25rem; height: 1.25rem; accent-color: var(--clay); }
  @media print { body * { visibility: hidden; } #rec-box, #rec-box * { visibility: visible; } #rec-box { position: absolute; left: 0; top: 0; } }
</style>
</head>
<body>
<main>
  <a href="<?= $h($home) ?>"><?= $h($T['back']) ?></a>
  <h1><?= $h($T['title']) ?></h1>

  <?php if ($required && !$tfaOn): ?>
    <p class="msg warn" role="alert"><?= $h($T['tfa_required']) ?></p>
  <?php endif; ?>

  <!-- ───── Phone ───── -->
  <section aria-labelledby="h-phone">
    <h2 id="h-phone"><?= $h($T['phone_h']) ?></h2>
    <p id="phone-state">
      <?php if (!empty($user['phone_e164'])): ?>
        <?= $h($T['phone_is']) ?> <strong><?= $h(Phone::mask((string)$user['phone_e164'])) ?></strong> <span class="pill ok">✓</span>
      <?php else: ?>
        <?= $h($T['phone_none']) ?>
      <?php endif; ?>
    </p>
    <button type="button" class="btn" id="phone-change"><?= $h($T['phone_change']) ?></button>

    <form id="phone-form" hidden novalidate>
      <label for="ph-phone"><?= $h($T['phone_label']) ?></label>
      <input id="ph-phone" type="tel" inputmode="tel" autocomplete="tel" maxlength="30" placeholder="<?= $h($T['phone_ph']) ?>">
      <div class="row" style="margin-top:.75rem"><button class="btn primary" type="submit" id="ph-send"><?= $h($T['send']) ?></button><button class="btn" type="button" id="ph-cancel"><?= $h($T['cancel']) ?></button></div>
    </form>
    <form id="code-form" hidden novalidate>
      <p id="ph-sent"></p>
      <label for="ph-code"><?= $h($T['code_label']) ?></label>
      <input id="ph-code" type="text" inputmode="numeric" autocomplete="one-time-code" maxlength="6" pattern="[0-9]*">
      <p class="msg warn" id="ph-dev" hidden></p>
      <div class="row" style="margin-top:.75rem"><button class="btn primary" type="submit" id="ph-verify"><?= $h($T['verify']) ?></button><button class="btn" type="button" id="ph-cancel2"><?= $h($T['cancel']) ?></button></div>
    </form>
    <p class="msg" id="phone-msg" role="status" hidden></p>
  </section>

  <!-- ───── SMS reminders ───── -->
  <section aria-labelledby="h-sms">
    <h2 id="h-sms"><?= $h($T['sms_h']) ?></h2>
    <p><?= $h($T['sms_p']) ?></p>
    <label class="toggle"><input type="checkbox" id="sms-optin" <?= $smsOptIn ? 'checked' : '' ?>><span id="sms-optin-label"><?= $h($smsOptIn ? $T['sms_on'] : $T['sms_off']) ?></span></label>
  </section>

  <!-- ───── Two-factor ───── -->
  <section aria-labelledby="h-tfa" id="tfa">
    <h2 id="h-tfa"><?= $h($T['tfa_h']) ?> <span class="pill <?= $tfaOn ? 'ok' : '' ?>" id="tfa-pill"><?= $h($tfaOn ? $T['tfa_on'] : $T['tfa_off']) ?></span></h2>
    <p><?= $h($T['tfa_p']) ?></p>

    <div id="tfa-off" <?= $tfaOn ? 'hidden' : '' ?>>
      <button type="button" class="btn primary" id="tfa-start"><?= $h($T['tfa_start']) ?></button>
      <div id="tfa-setup" hidden>
        <p><strong><?= $h($T['tfa_step1']) ?></strong></p>
        <div class="row" style="align-items:flex-start">
          <div class="qr" id="tfa-qr" role="img" aria-label="QR code"></div>
          <div>
            <p><?= $h($T['tfa_manual']) ?></p>
            <p class="secret" id="tfa-secret"></p>
            <p><a id="tfa-link" href="#"><?= $h($T['tfa_open']) ?></a></p>
          </div>
        </div>
        <form id="tfa-confirm-form" novalidate>
          <p><strong><?= $h($T['tfa_step2']) ?></strong></p>
          <label for="tfa-code"><?= $h($T['code']) ?></label>
          <input id="tfa-code" type="text" inputmode="numeric" autocomplete="one-time-code" maxlength="6" pattern="[0-9]*">
          <div class="row" style="margin-top:.75rem"><button class="btn primary" type="submit" id="tfa-confirm"><?= $h($T['tfa_confirm']) ?></button></div>
        </form>
      </div>
    </div>

    <div id="rec-box" hidden>
      <h2 style="margin-top:1rem"><?= $h($T['rec_h']) ?></h2>
      <p><?= $h($T['rec_p']) ?></p>
      <ul class="codes" id="rec-list"></ul>
      <div class="row">
        <button type="button" class="btn" id="rec-copy"><?= $h($T['rec_copy']) ?></button>
        <button type="button" class="btn" id="rec-dl"><?= $h($T['rec_dl']) ?></button>
        <button type="button" class="btn" id="rec-print"><?= $h($T['rec_print']) ?></button>
      </div>
      <label class="toggle" style="margin-top:.75rem"><input type="checkbox" id="rec-saved"><span><?= $h($T['rec_saved']) ?></span></label>
    </div>

    <div id="tfa-on" <?= $tfaOn ? '' : 'hidden' ?>>
      <p><?= $h($T['rec_left']) ?> <strong id="rec-left"><?= (int)$recoveryLeft ?></strong></p>

      <form id="rec-new-form" novalidate>
        <label for="rec-new-code"><?= $h($T['rec_new']) ?></label>
        <p style="margin-top:0"><?= $h($T['rec_new_hint']) ?></p>
        <input id="rec-new-code" type="text" inputmode="numeric" autocomplete="one-time-code" maxlength="6" pattern="[0-9]*">
        <div class="row" style="margin-top:.75rem"><button class="btn" type="submit"><?= $h($T['rec_new']) ?></button></div>
      </form>

      <form id="dis-form" novalidate style="margin-top:1.5rem">
        <h2><?= $h($T['dis_h']) ?></h2>
        <p><?= $h($T['dis_p']) ?></p>
        <label for="dis-pw"><?= $h($T['pw']) ?></label>
        <input id="dis-pw" type="password" autocomplete="current-password">
        <label for="dis-code"><?= $h($T['code']) ?></label>
        <input id="dis-code" type="text" inputmode="text" autocomplete="one-time-code" maxlength="12">
        <div class="row" style="margin-top:.75rem"><button class="btn danger" type="submit"><?= $h($T['dis_btn']) ?></button></div>
      </form>
    </div>
    <p class="msg" id="tfa-msg" role="status" hidden></p>
  </section>
</main>

<script src="/assets/vendor/qrcode-generator.js"></script>
<script>
(function () {
  'use strict';
  const T = <?= json_encode($T, JSON_UNESCAPED_UNICODE | JSON_HEX_TAG | JSON_HEX_AMP) ?>;
  const $ = (id) => document.getElementById(id);
  const post = (url, data) => {
    const fd = new FormData(); Object.keys(data).forEach(k => fd.append(k, data[k]));
    return fetch(url, { method: 'POST', body: fd, credentials: 'same-origin' })
      .then(r => r.json().catch(() => ({ success: false, message: T.net })))
      .catch(() => ({ success: false, message: T.net }));
  };
  const say = (el, text, kind) => { el.textContent = text; el.className = 'msg ' + (kind || ''); el.hidden = !text; };

  /* ---- phone ---- */
  const pm = $('phone-msg');
  const showPhone = (step) => { $('phone-form').hidden = step !== 'phone'; $('code-form').hidden = step !== 'code'; $('phone-change').hidden = step !== 'idle'; };
  $('phone-change').addEventListener('click', () => { say(pm, ''); showPhone('phone'); $('ph-phone').focus(); });
  [$('ph-cancel'), $('ph-cancel2')].forEach(b => b.addEventListener('click', () => { say(pm, ''); showPhone('idle'); }));
  $('phone-form').addEventListener('submit', async (e) => {
    e.preventDefault(); say(pm, '');
    $('ph-send').disabled = true;
    const d = await post('/api/phone.php', { action: 'start', phone: $('ph-phone').value.trim() });
    $('ph-send').disabled = false;
    if (!d.success) { say(pm, d.message, 'err'); return; }
    $('ph-sent').textContent = T.sent.replace(':phone', d.phone_masked || '');
    const dev = $('ph-dev'); if (d.dev_code) { dev.textContent = 'Dev: ' + d.dev_code; dev.hidden = false; } else dev.hidden = true;
    showPhone('code'); $('ph-code').value = ''; $('ph-code').focus();
  });
  $('ph-code').addEventListener('input', (e) => { e.target.value = e.target.value.replace(/\D+/g, '').slice(0, 6); });
  $('code-form').addEventListener('submit', async (e) => {
    e.preventDefault(); say(pm, '');
    $('ph-verify').disabled = true;
    const d = await post('/api/phone.php', { action: 'verify', code: $('ph-code').value });
    $('ph-verify').disabled = false;
    if (!d.success) { say(pm, d.message, 'err'); return; }
    $('phone-state').innerHTML = ''; const s = document.createElement('span'); s.textContent = T.phone_is + ' '; const b = document.createElement('strong'); b.textContent = d.phone_masked; $('phone-state').append(s, b, ' ✓');
    showPhone('idle'); say(pm, T.phone_saved, 'ok');
  });

  /* ---- SMS reminders ---- */
  $('sms-optin').addEventListener('change', async (e) => {
    const on = e.target.checked;
    const d = await post('/api/phone.php', { action: 'optin', value: on ? '1' : '0' });
    if (!d.success) { e.target.checked = !on; return; }
    $('sms-optin-label').textContent = on ? T.sms_on : T.sms_off;
  });

  /* ---- two-factor ---- */
  const tm = $('tfa-msg');
  let recoveryCodes = [];
  function qrSvg(text) {
    const q = window.qrcode(0, 'M'); q.addData(text); q.make();
    const n = q.getModuleCount(), m = 2, size = n + m * 2; let d = '';
    for (let r = 0; r < n; r++) for (let c = 0; c < n; c++) if (q.isDark(r, c)) d += 'M' + (c + m) + ' ' + (r + m) + 'h1v1h-1z';
    return '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ' + size + ' ' + size + '" shape-rendering="crispEdges"><rect width="' + size + '" height="' + size + '" fill="#fff"/><path d="' + d + '" fill="#1E1B16"/></svg>';
  }
  function showRecovery(codes) {
    recoveryCodes = codes;
    const ul = $('rec-list'); ul.innerHTML = '';
    codes.forEach(c => { const li = document.createElement('li'); li.textContent = c; ul.appendChild(li); });
    $('rec-box').hidden = false; $('rec-saved').checked = false;
    $('rec-box').scrollIntoView({ behavior: 'smooth', block: 'center' });
  }
  $('tfa-start').addEventListener('click', async () => {
    say(tm, ''); $('tfa-start').disabled = true;
    const d = await post('/api/2fa.php', { action: 'begin' });
    $('tfa-start').disabled = false;
    if (!d.success) { say(tm, d.message, 'err'); return; }
    $('tfa-qr').innerHTML = qrSvg(d.uri);
    $('tfa-secret').textContent = d.secret.replace(/(.{4})/g, '$1 ').trim();
    $('tfa-link').href = d.uri;
    $('tfa-start').hidden = true; $('tfa-setup').hidden = false; $('tfa-code').focus();
  });
  $('tfa-code').addEventListener('input', (e) => { e.target.value = e.target.value.replace(/\D+/g, '').slice(0, 6); });
  $('tfa-confirm-form').addEventListener('submit', async (e) => {
    e.preventDefault(); say(tm, ''); $('tfa-confirm').disabled = true;
    const d = await post('/api/2fa.php', { action: 'confirm', code: $('tfa-code').value });
    $('tfa-confirm').disabled = false;
    if (!d.success) { say(tm, d.message, 'err'); return; }
    $('tfa-off').hidden = true; $('tfa-on').hidden = false;
    $('tfa-pill').textContent = T.tfa_on; $('tfa-pill').className = 'pill ok';
    $('rec-left').textContent = String(d.recovery_codes.length);
    showRecovery(d.recovery_codes); say(tm, T.on_done, 'ok');
  });
  $('rec-new-form').addEventListener('submit', async (e) => {
    e.preventDefault(); say(tm, '');
    const d = await post('/api/2fa.php', { action: 'recovery', code: $('rec-new-code').value });
    if (!d.success) { say(tm, d.message, 'err'); return; }
    $('rec-new-code').value = ''; $('rec-left').textContent = String(d.recovery_codes.length); showRecovery(d.recovery_codes);
  });
  $('dis-form').addEventListener('submit', async (e) => {
    e.preventDefault(); say(tm, '');
    if (!confirm(T.confirm_dis)) return;
    const d = await post('/api/2fa.php', { action: 'disable', password: $('dis-pw').value, code: $('dis-code').value });
    if (!d.success) { say(tm, d.message, 'err'); return; }
    $('dis-pw').value = ''; $('dis-code').value = '';
    $('tfa-on').hidden = true; $('rec-box').hidden = true; $('tfa-off').hidden = false; $('tfa-start').hidden = false; $('tfa-setup').hidden = true;
    $('tfa-pill').textContent = T.tfa_off; $('tfa-pill').className = 'pill';
    say(tm, T.dis_done, 'ok');
  });
  $('rec-copy').addEventListener('click', async () => { try { await navigator.clipboard.writeText(recoveryCodes.join('\n')); say(tm, T.rec_copied, 'ok'); } catch (e) {} });
  $('rec-print').addEventListener('click', () => window.print());
  $('rec-dl').addEventListener('click', () => {
    const a = document.createElement('a');
    a.href = URL.createObjectURL(new Blob(['StudyVibe recovery codes\n\n' + recoveryCodes.join('\n') + '\n'], { type: 'text/plain' }));
    a.download = 'studyvibe-recovery-codes.txt'; a.click(); setTimeout(() => URL.revokeObjectURL(a.href), 1000);
  });
  window.addEventListener('beforeunload', (e) => { if (!$('rec-box').hidden && !$('rec-saved').checked) { e.preventDefault(); e.returnValue = ''; } });
})();
</script>
</body>
</html>
